### ISSUE TITLE
fog heat client don't populate correctly the "files" parameter

### ISSUE THREAD

**Issue by ioggstream** [fog/fog-openstack#313]
# Reproduce

Create an Orchestration template that references external files:

```
heat_template_version: newton

resources:
  a_file:
    type: https://gist.githubusercontent.com/ioggstream/55135a3c886802dedaac833ce4f87bfa/raw/b320d97756da702797d76b85b0a8c630d5589889/case_01891685.yaml

 #  https://pastebin.com/raw/hVbif6z9
 # the linked resource references get_file: https://www.google.com/robots.txt

```

# I expect 

- the stack to be created

# Instead

- I got an error
- Heat complains about `get_file: https://www.google.com/robots.txt` not in the files dict
- getting the files dict from heat, the file is not there

```
openstack stack files list mystack
...
NO https://www.google.com/robots.txt around
``` 

Here's the Heat API reference https://developer.openstack.org/api-ref/orchestration/v1/index.html?expanded=create-stack-detail#stacks

And here's the fog/fog-openstack file

  - there's no `files` parameter  https://github.com/fog/fog-openstack/blame/master/lib/fog/orchestration/openstack/models/stack.rb#L9

  - there's no `files` resolution here https://github.com/fog/fog-openstack/blob/master/lib/fog/orchestration/openstack/requests/create_stack.rb

This  snippet - very simple and without proper error handling - should resolve `get_file` in  nested templates https://gist.github.com/ioggstream/bedea98dc53aa61b0ebd48cd1bb73486

Here's the python-heatclient implementation 

https://github.com/openstack/python-heatclient/blob/master/heatclient/common/template_utils.py#L103
