### ISSUE TITLE
Failing unit tests locally

### ISSUE THREAD

**Issue by timuralp** [fog/fog-openstack#350]
Looks like I'm unable to run unit tests locally without failure, as the following tests fail:
```
Fog::Orchestration[:openstack] | stack requests::success#test_0005_#recurse_template_and_file
Fog::Orchestration[:openstack] | stack requests::success#test_0002_#get_file_contents_local_template
```
In both cases, the failure is:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - ///home/travis/build/fog/fog-openstack/test/requests/orchestration/no_recursion.yaml
```

I looked through the changes there, and it looks like it's related to the following change (from 2b32ce8b3d000b20d196601ddbda048d9a463554):
```
diff --git a/lib/fog/orchestration/util/recursive_hot_file_loader.rb b/lib/fog/orchestration/util/recursive_hot_file_loader.rb
index 1de6f15..9361588 100644
--- a/lib/fog/orchestration/util/recursive_hot_file_loader.rb
+++ b/lib/fog/orchestration/util/recursive_hot_file_loader.rb
@@ -123,10 +117,8 @@ module Fog
-            # Don't process file:// outside our base_url. TODO raise an exception here?
-            next if file_outside_base_url?(base_url, str_url)
 
-            file_content = get_content(str_url)
+            file_content = read_uri(str_url)
```

@ioggstream, could you look into this? My understanding is that there is a .yaml template that specifies a URL that conflicts with the base URL used. Previously, this would be skipped over (with a possible TODO for an exception), but now fetching there is an implicit requirement to recreate the `/home/travis/...` build path. I think the solution here could be to mock out the file, verify the path, and return contents from `$FOG_OPENSTACK/test/requests/orchestration/no_recursion.yaml`.

**Comment by ioggstream** [comment]
@timuralp 

The issue you pointed out is not in the library code you referenced but in the test. 

While
 - you can try patching the *test code* (but not the library code) with a clever resolution of $FOG_OPENSTACK/test/... that should work both in travis and on your PC.

I suggest you to either:
 - (not my choiche) create/link/sed /home/travis path  
 - (my choice) developing in a ruby docker container. This allows run tests on different ruby versions in a shot (which I always did).

```

cat >  docker-compose.yml << EOF 
version: '2'

services:

  ruby:
    image: ruby
    entrypoint: tail -f /etc/hosts
    cap_add:
    - SYS_PTRACE
    volumes:
    - .:/code:z
    - .:/home/travis/build/fog/fog-openstack:z
EOF

docker-compose up -d 
docker exec -ti fogopenstack_ruby_1 /bin/bash
```
